kind: pipeline
type: docker
name: node

steps:
  # - name: run
  #   pull: if-not-exists
  #   image: node:16
  #   commands:
  #     - echo hello
  #     - npm install
  - name: docker
    image: plugins/docker
    settings:
      repo: shoom1337/test
      username: shoom1337
      password: e3967e22-b813-41eb-b7e9-6cd017cf1bf4
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TG_BOT_TOKEN
      to:
        from_secret: TG_USER_ID
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed.(( Fix me please.
        {{/success}}
