kind: pipeline
type: docker
name: node

steps:
  - name: run
    pull: if-not-exists
    image: node:16
    commands:
      - echo hello
      - npm install
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: 5136625822:AAH936M8ExeTkahhZaxBS_LGzEfkmH8K1XI
      to: 548278998
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
